# Generated by Django 4.2 on 2023-12-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures-upload/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='picture',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='report-upload/%Y/%m/%d/'),
        ),
    ]
