# Generated by Django 4.2 on 2024-01-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.IntegerField(default=0),
        ),
    ]
