# Generated by Django 4.2 on 2024-01-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0004_alter_customuser_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
