# Generated by Django 4.2 on 2024-01-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0006_zone_appointment_desiredtime_appointment_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='designation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
